const CHART_SIZE = 200;
const STROKE_WIDTH = 36;
const RADIUS = (CHART_SIZE - STROKE_WIDTH) / 2;
const CIRCUMFERENCE = 2 * Math.PI * RADIUS;
const CENTER = CHART_SIZE / 2;
const SEGMENT_GAP = 2;

export { CHART_SIZE, STROKE_WIDTH, RADIUS, CIRCUMFERENCE, CENTER, SEGMENT_GAP };
